### PR TITLE
Rent form error

### PR DESCRIPTION
**Pull request by davidwessman**
There was a bad link and some unimported CSS

### CODE REVIEW

**Comment by jforberg** [comment]
'datetimepicker-rails' is not doing a very good job IMO. The style is pretty FU and also it shows dates with British format, i.e. %m/%d/%Y. We should probably look at the configuration to see if it's done right.

fudates

**Comment by davidwessman** [comment]
Thought I looked it through, will look at it again :o

**Comment by davidwessman** [comment]
@jforberg What date format do we want to use?

**Comment by jforberg** [comment]
Today is 2015-09-08.

**Comment by davidwessman** [comment]
Please check out that the picker is working, I think I changed it all to the same helper.

**Comment by jforberg** [comment]
Looks good.

**Comment by davidwessman** [comment]
I managed to forget the actual css there.
But got a new PR with more layout setup where it will arrive.
For now they work better atleast 😄

**Pull request merged**
