### PR TITLE
Changing date-format to ISO8601, loading new appfiles

### LINKED ISSUE #99: FullCalendar broken, no events shows.
Seems like some deploy has broken the calendar, will look into it.

### PR DESCRIPTION
**Pull request by davidwessman**
Something has changed with Fullcalendar or our Date-format, but now it works again.

Fixes #99 (and #100, unless someone objects).

### CODE REVIEW

**Comment by Zofz** [comment]
I will leave the rest of the Hound issues for a full refactor of events.

**Comment by henrikssn** [comment]
Please add a test which would catch this, so it never happens again.

**Comment by davidwessman** [comment]
@henrikssn Will do.

**Comment by davidwessman** [comment]
The Hound-comments will have to be worked at in a refactor of the Event-module.

Are we ready to merge this?
Not sure what the best way to test the format of a date in a ```json-hash```but I made the test to check that the hash contains the date in the right format - which for now serves the purpose.

Since we have  Fullcalendar for a lot of Modules - Event, CarRent, Cafe, why should do some kind of handler for the json-feeds. But this works for now.

**Comment by henrikssn** [comment]
LGTM :)

**Comment by davidwessman** [comment]
@henrikssn  what about #100?

**Comment by davidwessman** [comment]
Latest commit fixes #100.
Will merge at 16.00 unless someone objects.

**Comment by henrikssn** [comment]
:+1:

**Comment by henrikssn** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/46' target='_blank'>4af782a</a>

**Comment by davidwessman** [comment]
Hmm. The event-calendar doesn't work properly when deployed.

And I run into this when I try to open the ```rails console``` as ```sudo su www-data```
https://www.dropbox.com/s/zbjgwjjp0s3vlmh/Sk%C3%A4rmklipp%202015-03-23%2016.32.36.png?dl=0

@henrikssn Any ideas?

**Comment by henrikssn** [comment]
Does it work on dev?

**Comment by davidwessman** [comment]
Hmm, I missed out that Fullcalendar sends it as_json request with options, and I didn't have that on Events, must have changed it after I tested it out. 

So I need to push again.

**Comment by davidwessman** [comment]
Gonna try to look into the Fullcalendar JS to write proper tests for the implementation of it.
Should I just make a new PR?

**Comment by henrikssn** [comment]
Yes

**Pull request merged**
