### PR TITLE
Don't send email in development mode.

### PR DESCRIPTION
**Pull request by jforberg**

### CODE REVIEW

**Comment by henrikssn** [comment]
LGTM

**Comment by davidwessman** [comment]
:+1:

**Comment by davidwessman** [comment]
Does it work to merge before the server is running?

**Comment by jforberg** [comment]
Well, nothing will get deployed if that's what you're asking. Merging happens locally at github.

**Comment by davidwessman** [comment]
Yeah - but then we have to babysit deployment when server is back up?

**Comment by jforberg** [comment]
Presumably.

**Pull request merged**
