### PR TITLE
Merge Cafebokning into master

### PR DESCRIPTION
**Pull request by davidwessman**
Reverts fsek/web#139

### CODE REVIEW

**Comment by davidwessman** [comment]
Gonna fix the menus

**Comment by davidwessman** [comment]
@henrikssn 
I do not really know how to write integration tests, and that is probably what would have caught this.

**Comment by henrikssn** [comment]
Read the wiki, try it, make PR and ask questions :)

**Comment by davidwessman** [comment]
@henrikssn I implemented the sign_in test and a test with an admin logging in, then adding a new menu.

**Comment by henrikssn** [comment]
Cool! LGTM :smile:

**Comment by SirDirac** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/76' target='_blank'>ce9a5f3</a>

**Comment by davidwessman** [comment]
The migration for CafeWork wasn't migrated. But there are a lot of error fixes in this PR and the CafeWork-module doesn't show before we link to it anyway.
Is it okay if we fix the migration in a separate PR? @henrikssn

**Comment by davidwessman** [comment]
Perhaps we have time to fix the #108 today?
I can add all the current migrations to the fsek_structure-migration and renumber it.
How do we get the current state of the servers schema.db?

**Comment by henrikssn** [comment]
Yes :)

Why wasn't it migrated?

**Comment by davidwessman** [comment]
Because it has number 27, and we have already run the permissions-migration which has number 47

**Comment by henrikssn** [comment]
I see. Didn't you get a merge conflict?

**Comment by davidwessman** [comment]
Nope - not in the deploy. Just when trying to go to http://fsektionen.se/hilbertcafe

**Comment by henrikssn** [comment]
Ok. Poke @jforberg about #108

**Pull request merged**
