### PR TITLE
Fix migration conflicts

### PR DESCRIPTION
**Pull request by davidwessman**
Merged #141 and the migration to create the CafeWorks-table was not run.

Current state of schema.rb:
https://gist.github.com/davidwessman/48a930a0ad00c8fb3de7

#108
@jforberg 
Should we move all the migrations into a file with similar structure as the fsek-structure and set this number to 0. Then we reset the numbers in the migrations-table on production.

### CODE REVIEW

**Comment by davidwessman** [comment]
I see here that the Permission-migrations haven't been run yet, either.

**Comment by davidwessman** [comment]
Created a ```database_structure```-migration in bd120db 
Checked the migration files after this and commented on them, the only one not in the current schema is the ```create_cafe_work```.

**Comment by henrikssn** [comment]
*Fingers crossed*

**Comment by davidwessman** [comment]
We have backup haha ;)

**Comment by henrikssn** [comment]
Pushing now...

**Comment by SirDirac** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/78' target='_blank'>a3a742e</a>

**Comment by henrikssn** [comment]
Yay :smile:

**Comment by davidwessman** [comment]
Looking good 😄 Good job! 😄 
Can you generate new Permissions for CafeWork? (not sure how we do this?) 
@henrikssn

**Comment by henrikssn** [comment]
Done. This is now done automatically in the future.

If you need to do it locally you run `rake permissions:load`

**Comment by davidwessman** [comment]
Nice 😄

**Pull request merged**
