### PR TITLE
Added gitter badge

### PR DESCRIPTION
**Pull request by henrikssn**
[Join the chat at https://gitter.im/fsek/web](https://gitter.im/fsek/web?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

### CODE REVIEW

**Comment by henrikssn** [comment]
1. It is nice to have all discussions in one place
2. You can connect with IRC, it is basically just a fancy IRC server
3. It was easy to integrate Travis so we get test results directly in the chat room

**Comment by jforberg** [comment]
"It is nice to have all discussions in one place"


1. Email
2. Facebook
3. Github
4. Google groups?
5. Gitter

Well, you seem to think this a good idea so go ahead. But if you need to reach me you should probably use any of (1-4).

**Comment by henrikssn** [comment]
Yaya, let's see how this works.

**Comment by SirDirac** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/101' target='_blank'>c444e74</a>

**Pull request merged**
