### PR TITLE
Update to rails 4.2.0

### PR DESCRIPTION
**Pull request by henrikssn**
This fixes all current security issues.

https://hakiri.io/github/fsek/web/security

### CODE REVIEW

**Comment by henrikssn** [comment]
Looks like the code needs some massage before we can merge this.

**Comment by Zofz** [comment]
@henrikssn Should I push the #57 solution here?

**Comment by Zofz** [comment]
@henrikssn Why doesn't Travis always run PR?

**Comment by Zofz** [comment]
@henrikssn Looks ready to merge if you fix the spec-styles. 
Good job! 😄

**Comment by Zofz** [comment]
@henrikssn We should bump ```coffee-rails ``` from ```~> 4.0.0 ``` to ```~> 4.1.0```

**Comment by henrikssn** [comment]
@Zofz Next time we bump coffee and sass :)

**Pull request merged**
