### PR TITLE
Rails 4.2.1 + update some gems

### PR DESCRIPTION
**Pull request by henrikssn**
Fixed all yellow markers https://gemnasium.com/fsek/web

### CODE REVIEW

**Comment by Zofz** [comment]
I really like the structure you put up for all the project, 4-5 months ago we used a local git, barely used branches and had no issue-tracking, code-review or anything.

And this goes out to all @fsek/admins, great work 😄 
We should just get the rest of the team to do some assignments as well ;) 

And it is much more fun to be able to collaborate for real 😄 I'm learning a lot!
(Sorry for all the errors I cause, hopefully they will come with a lower frequency after a while ;) )

**Comment by Zofz** [comment]
I never get when the:
https://github.com/fsek/web/blob/master/spec/features/home_spec.rb
fails, it seems kind of random.

**Comment by henrikssn** [comment]
@Zofz Yeah the best thing with code-reviews is really how much you can learn from each other

**Comment by henrikssn** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/43' target='_blank'>bf4e7ab</a>

**Pull request merged**
