### PR TITLE
Rake task to add first user as admin

### PR DESCRIPTION
**Pull request by henrikssn**
We need to have a (manage all) permission and a (admin) post in the database to create an admin user.

I am not sure if to actually create the admin user or not. Come with feedback.

### CODE REVIEW

**Comment by henrikssn** [comment]
Thing is, there is no way to do this except from the console in a app where the database have been reset, as there are no admin users and it is impossible to create an admin user without having one. That is bad.

How did the "assign the first registered user as admin" we had before work?

**Comment by davidwessman** [comment]
Devise have an option to set the first registering user as admin I think.

**Comment by henrikssn** [comment]
Not really... I moved this to a rake task, you now register a user and run `rake promote_admin`. The user with id 1 will become admin.

**Comment by davidwessman** [comment]
Is there no validation for a council on a post? 
Otherwise LGTM

**Comment by SirDirac** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/91' target='_blank'>20e788c</a>

**Pull request merged**
