### PR TITLE
Revert "Implementing closing date for Election"

### PR DESCRIPTION
**Pull request by davidwessman**
Reverts fsek/web#173

Not sure why it failed:
http://samson.fsektionen.se/projects/web/deploys/98

### CODE REVIEW

**Comment by henrikssn** [comment]
You don't need to revert, it hasn't deployed sine deploy failed

**Comment by henrikssn** [comment]
I'll fix it, stand by

**Comment by henrikssn** [comment]
Seems the Debian upgrade broke some stuff. Let's see if this worked...

http://samson.fsektionen.se/projects/web/deploys/100

**Comment by henrikssn** [comment]
Fixed

**Comment by davidwessman** [comment]
Cheers 😄

**Pull request closed without merging**
