### PR TITLE
Update lots of gems

### PR DESCRIPTION
**Pull request by henrikssn**

### CODE REVIEW

**Comment by Zofz** [comment]
Does this PR cover #56 now as well?

**Comment by henrikssn** [comment]
#56 is already merged. This covers fixes we need to make before things work with the latest gems.

I had to fix an error in news for #56 which did not show up in tests. I'll try to make an integration test for that.

**Comment by Zofz** [comment]
The test-base is not that good(read not existing) on the old models.

**Comment by henrikssn** [comment]
This now works fine on dev and all tests pass.

**Pull request merged**
