### PR TITLE
Removing old tests

### LINKED ISSUE #65: Test fail: undefined method `validate_acceptance_of' for RentTest:Class
NoMethodError: undefined method `validate_acceptance_of' for RentTest:Class
/home/johan/code/fsek/test/models/rent_test.rb:5:in `<class:RentTest>'

@Zofz är skyldigt enligt git blame

### PR DESCRIPTION
**Pull request by Zofz**
Some old test was failing in a build.
Most is already merged to Rspec.

Closes #65.

### CODE REVIEW

**Comment by henrikssn** [comment]
LGTM

**Comment by Zofz** [comment]
@henrikssn Not sure what you mean with that ;)

**Comment by henrikssn** [comment]
Looks Good To Me :)

**Comment by Zofz** [comment]
@henrikssn My guess was on ```legitimate```, but wouldn't make any sense to shorten that! ;) 
Anyone feel free to merge, we are working on more ~~tests~~ specs on #70.

**Comment by Zofz** [comment]
Solved in #70 which is merged with master.

**Pull request closed without merging**
