### PR TITLE
Changing the scope for active rents to not exclude service-marked rents

### PR DESCRIPTION
**Pull request by Zofz**
Pushed this to master yesterday, it disappeared again.
As title says.

### CODE REVIEW

**Comment by Zofz** [comment]
Anyone feel free to merge if or when tests pass.

**Comment by henrikssn** [comment]
Please fix style before merge

**Comment by Zofz** [comment]
@henrikssn What has changed with the databas.yml? Cannot run my tests locally because it doesn't load the database configuration.

**Comment by henrikssn** [comment]
David: För att inte ha lösenordet till mysql på internet. Kör rake db:migrate så får du en config som fungerar :)




Erik



—
Erik Henriksson
erik.henriksson@me.com
+41 789 61 22 26

**Comment by Zofz** [comment]
Så det kan bli när man inte testar i webbläsaren ens... ;)

**Pull request merged**
