### PR TITLE
Deploy system

### PR DESCRIPTION
**Pull request by henrikssn**
This introduces our new deploy system, which you can take a quick look at here: http://samson.fsektionen.se

It will
* Run tests and make sure they pass
* Run bundle, migrations and so on
* Deploy new version

All with a fancy web interface :)

### CODE REVIEW

**Comment by Zofz** [comment]
@henrikssn Something is not good with the development deploy, there is double app folders, nested in each other.

**Comment by Zofz** [comment]
@henrikssn fsektionen.se is down.
I tried to install bundle (as www-data) on dev, but I did not think that would affect the production server?

**Comment by henrikssn** [comment]
Ok, I did not bother to fix it as I was almost done.

It is up again on the new deploy system. Dev is coming next and after that instructions.

**Comment by henrikssn** [comment]
Getting server back up >> Hound fixes

**Pull request merged**
