### PR TITLE
Replace the commit number with badges

### PR DESCRIPTION
**Pull request by henrikssn**
This also allows us to get rid of the git_commit hack.

### CODE REVIEW

**Comment by jforberg** [comment]
Yes

**Comment by henrikssn** [comment]
Woop woop hound is my buddy this time

**Comment by Zofz** [comment]
Crazy - no hound issues? ;) 
Good job 😄

**Comment by henrikssn** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/40' target='_blank'>b5f5584</a>

**Pull request merged**
